Add resource owner password credentials grant support
yaegashi/msgraph.go pull request #13
Opened 2020-03-25 03:36 UTC by charlesgreen

Hello @yaegashi, 

Great project. It's very helpful. 

I added support for Resource Owner Password Credentials in a project I'm using.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

Please let me know if you'd like me to make any changes. 
Again, great work!

2020-03-25 21:01 UTC, yaegashi requested changes
Hi, thanks for the patch!

Could you add the reference and a code snippet like other grant flows in README.md?

<pre>
### Resource owner password credentials grant

- [OAuth 2.0 resource owner passowrd credentials grant flow]

```go
// code snippet
```

[OAuth 2.0 resource owner passowrd credentials grant flow]: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc
</pre>

2020-03-25 21:01 UTC, yaegashi commented on msauth/resource_owner_password_grant.go
> +	}
```suggestion
	t, err := config.PasswordCredentialsToken(ctx, username, password)
	if err != nil {
		return nil, err
	}
	ts := config.TokenSource(ctx, t)
```

- `var err error` is unneeded.
- It should return immediately if it gets an error.  `t` might cause nil pointer dereference.

2020-03-26 08:29 UTC, charlesgreen commented on msauth/resource_owner_password_grant.go
> +	}
Thanks for the feedback. I've made the changes and updated the README.

2020-03-26 09:13 UTC, yaegashi commented on msauth/resource_owner_password_grant.go
> +	}
Looks great.  Thank you!

2020-03-26 09:17 UTC, yaegashi approved these changes

2020-03-26 09:19 UTC, yaegashi commented
Thank you for your contribution!

2020-03-26 09:19 UTC, merged